server:
  port: ${PORT:8820}
spring:
  application:
    name: qa-service-2
#  cloud:
#    config:
#      uri: ${CONFIG_SERVER_URL:http://localhost:8710}
#      discovery:
#        enabled: true
#        serviceId: user-service
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    health-check-url-path: /actuator/health
    metadata-map:
      startup: ${random.int}    #needed to trigger info and endpoint update after restart
  client: #<1>
    serviceUrl:
      defaultZone: http://localhost:8700/eureka/
    fetchRegistry: true
    registryFetchIntervalSeconds: 5
    registerWithEureka: true
    healthcheck:
          enabled: false
ribbon:
  eureka:
    enabled: true