server:
  port: 8740
spring:
  application:
    name: mirror-server

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8700/eureka/}
    registerWithEureka: true
    fetchRegistry: true

zuul:
  routes:
    service2:
      path: /service2/**
      url: http://localhost:8920/

mirrorserver:
  primaryserver: http://localhost:8730
